/* Generated by tools/extract-hornet.py from Silksong's own sprites: do not edit by hand.
   Each move: assets/hornet/<name>.png, n cells of w × h px (at a third of the game's size, shown
   at half), fps, her pivot at (px, py) in each cell, and loopStart; FLOOR: her feet below the
   pivot when standing. */
globalThis.HK = globalThis.HK || {};
HK.HORNET = {
  FLOOR: 33,
  MOVES: {
    "idle": {"n": 6, "fps": 12.0, "w": 65, "h": 76, "px": 33, "py": 41, "loop": 0},
    "run": {"n": 10, "fps": 15.0, "w": 57, "h": 70, "px": 28, "py": 35, "loop": 0},
    "sprint": {"n": 8, "fps": 16.0, "w": 64, "h": 58, "px": 27, "py": 23, "loop": 0},
    "skid": {"n": 6, "fps": 15.0, "w": 69, "h": 76, "px": 36, "py": 40, "loop": 0},
    "turn": {"n": 6, "fps": 18.0, "w": 76, "h": 80, "px": 28, "py": 43, "loop": 0},
    "dash": {"n": 9, "fps": 16.0, "w": 84, "h": 52, "px": 51, "py": 19, "loop": 0},
    "jump": {"n": 17, "fps": 22.0, "w": 98, "h": 129, "px": 43, "py": 72, "loop": 0},
    "fall": {"n": 7, "fps": 15.0, "w": 57, "h": 68, "px": 28, "py": 31, "loop": 4},
    "land": {"n": 14, "fps": 24.0, "w": 70, "h": 79, "px": 37, "py": 41, "loop": 0},
    "hardland": {"n": 12, "fps": 12.0, "w": 69, "h": 79, "px": 39, "py": 41, "loop": 0},
    "float-open": {"n": 3, "fps": 16.0, "w": 76, "h": 80, "px": 44, "py": 40, "loop": 0},
    "float": {"n": 11, "fps": 12.0, "w": 70, "h": 89, "px": 39, "py": 41, "loop": 0},
    "throw-antic": {"n": 3, "fps": 20.0, "w": 75, "h": 78, "px": 29, "py": 42, "loop": 0},
    "throw": {"n": 3, "fps": 20.0, "w": 50, "h": 63, "px": 31, "py": 30, "loop": 0},
    "pull": {"n": 1, "fps": 30.0, "w": 66, "h": 45, "px": 34, "py": 22, "loop": 0},
    "catch": {"n": 2, "fps": 20.0, "w": 90, "h": 42, "px": 57, "py": 24, "loop": 0},
    "challenge": {"n": 10, "fps": 12.0, "w": 145, "h": 70, "px": 65, "py": 34, "loop": 5},
    "taunt": {"n": 23, "fps": 24.0, "w": 93, "h": 78, "px": 58, "py": 41, "loop": 0},
    "taunt-back": {"n": 11, "fps": 12.0, "w": 91, "h": 89, "px": 22, "py": 50, "loop": 6},
    "needolin-start": {"n": 6, "fps": 15.0, "w": 69, "h": 82, "px": 32, "py": 40, "loop": 0},
    "needolin": {"n": 11, "fps": 12.0, "w": 37, "h": 78, "px": 16, "py": 40, "loop": 0},
    "look-up": {"n": 7, "fps": 12.0, "w": 65, "h": 73, "px": 33, "py": 38, "loop": 1},
    "flourish": {"n": 7, "fps": 12.0, "w": 47, "h": 74, "px": 20, "py": 39, "loop": 0},
    "parry": {"n": 7, "fps": 15.0, "w": 76, "h": 69, "px": 44, "py": 29, "loop": 4},
    "sit": {"n": 4, "fps": 12.0, "w": 75, "h": 78, "px": 41, "py": 39, "loop": 0},
    "soar-antic": {"n": 6, "fps": 18.0, "w": 63, "h": 85, "px": 33, "py": 39, "loop": 3},
    "soar-throw": {"n": 5, "fps": 18.0, "w": 54, "h": 92, "px": 22, "py": 56, "loop": 0},
    "soar": {"n": 3, "fps": 18.0, "w": 28, "h": 63, "px": 10, "py": 26, "loop": 0},
    "soar-charge": {"n": 10, "fps": 18.0, "w": 133, "h": 61, "px": 50, "py": 35, "loop": 5},
    "soar-wait": {"n": 3, "fps": 12.0, "w": 52, "h": 51, "px": 19, "py": 15, "loop": 0},
    "soar-jump": {"n": 5, "fps": 18.0, "w": 51, "h": 52, "px": 18, "py": 15, "loop": 0},
    "leap": {"n": 9, "fps": 15.0, "w": 79, "h": 74, "px": 36, "py": 35, "loop": 5},
    "backflip": {"n": 19, "fps": 26.0, "w": 91, "h": 77, "px": 44, "py": 37, "loop": 12},
    "float-close": {"n": 2, "fps": 20.0, "w": 78, "h": 68, "px": 42, "py": 39, "loop": 0},
    "catch-back": {"n": 2, "fps": 20.0, "w": 50, "h": 63, "px": 31, "py": 30, "loop": 0},
    "mantle-cling": {"n": 5, "fps": 25.0, "w": 77, "h": 102, "px": 25, "py": 44, "loop": 0},
    "mantle-vault": {"n": 3, "fps": 30.0, "w": 75, "h": 77, "px": 34, "py": 26, "loop": 0},
    "mantle-land": {"n": 2, "fps": 25.0, "w": 76, "h": 54, "px": 41, "py": 16, "loop": 0},
    "mantle-stand": {"n": 6, "fps": 18.0, "w": 73, "h": 76, "px": 36, "py": 40, "loop": 0},
    "harpoon-needle": {"n": 3, "fps": 20.0, "w": 131, "h": 11, "px": 52, "py": 5, "loop": 0, "boxes": [[8, 2, 119, 7], [11, 2, 93, 7], [26, 2, 75, 7]]},
    "harpoon-thread": {"n": 6, "fps": 30.0, "w": 123, "h": 33, "px": 61, "py": 17, "loop": 0, "boxes": [null, null, [46, 17, 64, 3], [7, 17, 109, 4], [50, 10, 61, 15], [59, 3, 58, 27]]},
    "needle-hit": {"n": 6, "fps": 20.0, "w": 97, "h": 16, "px": 43, "py": 8, "loop": 0, "boxes": [[2, 5, 93, 7], [11, 2, 75, 9], [14, 5, 75, 9], [14, 4, 75, 7], [17, 5, 75, 7], [17, 5, 75, 7]]},
    "soar-thread": {"n": 16, "fps": 30.0, "w": 35, "h": 157, "px": 16, "py": 75, "loop": 0, "boxes": [null, null, [5, 24, 24, 119], [5, 20, 25, 127], [11, 35, 11, 116], [9, 24, 11, 128], [11, 16, 8, 131], [13, 11, 7, 141], [10, 16, 12, 133], [9, 14, 11, 138], [11, 12, 8, 138], [13, 15, 6, 122], [11, 21, 6, 128], [15, 38, 3, 111], [14, 42, 3, 107], [14, 37, 2, 78]]}
  }
};
