/* Generated by tools/extract-knight.py from the game's own sprites: do not edit by hand.
   Each move: assets/knight/<name>.png, n cells of w × h px (the game's size, 64 px a unit),
   fps, his pivot at (px, py) in each cell, and loopStart (-1: plays once); FLOOR: his feet
   below the pivot when standing. */
globalThis.HK = globalThis.HK || {};
HK.KNIGHT = {
  FLOOR: 90,
  MOVES: {
    "idle": {"n": 9, "fps": 12.0, "w": 65, "h": 134, "px": 36, "py": 42, "loop": 0},
    "turn": {"n": 2, "fps": 20.0, "w": 76, "h": 130, "px": 35, "py": 37, "loop": -1},
    "run": {"n": 13, "fps": 12.0, "w": 89, "h": 134, "px": 38, "py": 42, "loop": 6},
    "run-stop": {"n": 6, "fps": 24.0, "w": 76, "h": 134, "px": 40, "py": 41, "loop": -1},
    "sit": {"n": 3, "fps": 10.0, "w": 90, "h": 149, "px": 52, "py": 60, "loop": -1},
    "sit-idle": {"n": 1, "fps": 30.0, "w": 83, "h": 132, "px": 45, "py": 56, "loop": 0},
    "sit-lean": {"n": 3, "fps": 12.0, "w": 94, "h": 148, "px": 57, "py": 57, "loop": -1},
    "doze": {"n": 2, "fps": 12.0, "w": 89, "h": 131, "px": 42, "py": 55, "loop": -1},
    "asleep": {"n": 1, "fps": 30.0, "w": 85, "h": 121, "px": 38, "py": 45, "loop": -1},
    "wake-sit": {"n": 9, "fps": 12.0, "w": 88, "h": 137, "px": 47, "py": 61, "loop": -1},
    "get-off": {"n": 5, "fps": 12.0, "w": 95, "h": 144, "px": 49, "py": 52, "loop": -1},
    "map-open": {"n": 4, "fps": 12.0, "w": 86, "h": 133, "px": 48, "py": 51, "loop": -1},
    "map-close": {"n": 5, "fps": 12.0, "w": 86, "h": 138, "px": 48, "py": 56, "loop": -1},
    "focus": {"n": 7, "fps": 12.0, "w": 78, "h": 130, "px": 38, "py": 39, "loop": 2},
    "focus-get": {"n": 11, "fps": 12.0, "w": 106, "h": 126, "px": 58, "py": 34, "loop": 6},
    "focus-end": {"n": 3, "fps": 12.0, "w": 75, "h": 130, "px": 35, "py": 39, "loop": -1},
    "slug-up": {"n": 4, "fps": 17.391, "w": 88, "h": 136, "px": 38, "py": 44, "loop": -1},
    "slug-idle": {"n": 5, "fps": 12.0, "w": 105, "h": 105, "px": 60, "py": 11, "loop": 0},
    "slug-idle-shell": {"n": 5, "fps": 12.0, "w": 107, "h": 106, "px": 62, "py": 11, "loop": 0},
    "slug-idle-spore": {"n": 5, "fps": 12.0, "w": 103, "h": 106, "px": 58, "py": 11, "loop": 0},
    "slug-idle-both": {"n": 5, "fps": 12.0, "w": 107, "h": 106, "px": 62, "py": 11, "loop": 0},
    "slug-down": {"n": 9, "fps": 12.0, "w": 105, "h": 139, "px": 60, "py": 44, "loop": 4}
  }
};
