/* js/rooms.js — GENERATED by tools/fetch-rooms.js (`npm run rooms`): don't edit by hand.
   The game's areas, each with its name as the game writes it (the text key alongside) and the
   area light it takes (css/tokens.css, --area-*); and which area each room (scene) is in, from
   the community randomizer's rooms.json. areaOf(scene) → the area id, or ''. Godhome's rooms
   (GG_*) are all Godhome. placeOf(scene) → the place inside its area (Mantis Village…), or ''. */
(() => {
  'use strict';
  const HK = globalThis.HK || (globalThis.HK = {});
  const AREAS = {
    'dirtmouth': { es: 'Bocasucia', en: 'Dirtmouth', light: 'dirtmouth' },   // MAP_NAME_DIRTMOUTH
    'crossroads': { es: 'Cruces Olvidados', en: 'Forgotten Crossroads', light: 'crossroads' },   // MAP_NAME_CROSSROADS
    'greenpath': { es: 'Sendero Verde', en: 'Greenpath', light: 'greenpath' },   // MAP_NAME_GREENPATH
    'fungal': { es: 'Páramos Fúngicos', en: 'Fungal Wastes', light: 'fungal' },   // MAP_NAME_FUNGAL_WASTES
    'fog': { es: 'Cañón Nublado', en: 'Fog Canyon', light: 'gardens' },   // MAP_NAME_FOG_CANYON
    'gardens': { es: 'Jardines de la Reina', en: 'Queen\'s Gardens', light: 'gardens' },   // MAP_NAME_ROYAL_GARDENS
    'city': { es: 'Ciudad de Lágrimas', en: 'City of Tears', light: 'city' },   // MAP_NAME_CITY
    'waterways': { es: 'Canales Reales', en: 'Royal Waterways', light: 'fungal' },   // MAP_NAME_WATERWAYS
    'crystal': { es: 'Cumbre de Cristal', en: 'Crystal Peak', light: 'crystal' },   // MAP_NAME_MINES
    'resting': { es: 'Tierras de Reposo', en: 'Resting Grounds', light: 'resting' },   // MAP_NAME_RESTING_GROUNDS
    'deepnest': { es: 'Nido Profundo', en: 'Deepnest', light: 'deepnest' },   // MAP_NAME_DEEPNEST
    'basin': { es: 'Cuenca Antigua', en: 'Ancient Basin', light: 'basin' },   // MAP_NAME_ABYSS
    'abyss': { es: 'El Abismo', en: 'The Abyss', light: 'abyss' },   // ABYSS_DEEP_SUPER + ABYSS_DEEP_MAIN
    'edge': { es: 'Límite del Reino', en: 'Kingdom\'s Edge', light: 'edge' },   // MAP_NAME_OUTSKIRTS
    'hive': { es: 'La Colmena', en: 'The Hive', light: 'hive' },   // HIVE_MAIN
    'colosseum': { es: 'Coliseo de los Insensatos', en: 'Colosseum Of Fools', light: 'colosseum' },   // COLOSSEUM_MAIN + COLOSSEUM_SUB
    'cliffs': { es: 'Acantilados Aulladores', en: 'Howling Cliffs', light: '' },   // MAP_NAME_CLIFFS
    'palace': { es: 'Palacio Blanco', en: 'White Palace', light: 'palace' },   // WHITE_PALACE_SUPER + WHITE_PALACE_MAIN
    'godhome': { es: 'Hogar de Dioses', en: 'Godhome', light: 'godhome' },   // GODHOME_MAIN
  };
  const BY_AREA = {
    dirtmouth: ['Grimm_Divine', 'Grimm_Main_Tent', 'Room_Bretta', 'Room_Ouiji', 'Room_Town_Stag_Station', 'Room_mapper', 'Room_shop', 'Town', 'Tutorial_01'],
    crossroads: ['Crossroads_01', 'Crossroads_02', 'Crossroads_03', 'Crossroads_04', 'Crossroads_05', 'Crossroads_06', 'Crossroads_07', 'Crossroads_08', 'Crossroads_09', 'Crossroads_10', 'Crossroads_11_alt', 'Crossroads_12', 'Crossroads_13', 'Crossroads_14', 'Crossroads_15', 'Crossroads_16', 'Crossroads_18', 'Crossroads_19', 'Crossroads_21', 'Crossroads_22', 'Crossroads_25', 'Crossroads_27', 'Crossroads_30', 'Crossroads_31', 'Crossroads_33', 'Crossroads_35', 'Crossroads_36', 'Crossroads_37', 'Crossroads_38', 'Crossroads_39', 'Crossroads_40', 'Crossroads_42', 'Crossroads_43', 'Crossroads_45', 'Crossroads_46', 'Crossroads_47', 'Crossroads_48', 'Crossroads_49', 'Crossroads_52', 'Crossroads_ShamanTemple', 'Mines_33', 'Room_Charm_Shop', 'Room_Mender_House', 'Room_ruinhouse', 'Room_temple'],
    greenpath: ['Fungus1_01', 'Fungus1_01b', 'Fungus1_02', 'Fungus1_03', 'Fungus1_04', 'Fungus1_05', 'Fungus1_06', 'Fungus1_07', 'Fungus1_08', 'Fungus1_09', 'Fungus1_10', 'Fungus1_11', 'Fungus1_12', 'Fungus1_13', 'Fungus1_14', 'Fungus1_15', 'Fungus1_16_alt', 'Fungus1_17', 'Fungus1_19', 'Fungus1_20_v02', 'Fungus1_21', 'Fungus1_22', 'Fungus1_25', 'Fungus1_26', 'Fungus1_29', 'Fungus1_30', 'Fungus1_31', 'Fungus1_32', 'Fungus1_34', 'Fungus1_35', 'Fungus1_36', 'Fungus1_37', 'Fungus1_Slug', 'Room_Slug_Shrine', 'Room_nailmaster_02'],
    fungal: ['Deepnest_01', 'Fungus2_01', 'Fungus2_02', 'Fungus2_03', 'Fungus2_04', 'Fungus2_05', 'Fungus2_06', 'Fungus2_07', 'Fungus2_08', 'Fungus2_09', 'Fungus2_10', 'Fungus2_11', 'Fungus2_12', 'Fungus2_13', 'Fungus2_14', 'Fungus2_15', 'Fungus2_17', 'Fungus2_18', 'Fungus2_19', 'Fungus2_20', 'Fungus2_21', 'Fungus2_23', 'Fungus2_26', 'Fungus2_28', 'Fungus2_29', 'Fungus2_30', 'Fungus2_31', 'Fungus2_32', 'Fungus2_33', 'Fungus2_34'],
    fog: ['Fungus3_01', 'Fungus3_02', 'Fungus3_03', 'Fungus3_24', 'Fungus3_25', 'Fungus3_25b', 'Fungus3_26', 'Fungus3_27', 'Fungus3_28', 'Fungus3_30', 'Fungus3_35', 'Fungus3_44', 'Fungus3_47', 'Fungus3_archive', 'Fungus3_archive_02', 'Room_Fungus_Shaman'],
    gardens: ['Deepnest_43', 'Fungus1_23', 'Fungus1_24', 'Fungus3_04', 'Fungus3_05', 'Fungus3_08', 'Fungus3_10', 'Fungus3_11', 'Fungus3_13', 'Fungus3_21', 'Fungus3_22', 'Fungus3_23', 'Fungus3_34', 'Fungus3_39', 'Fungus3_40', 'Fungus3_48', 'Fungus3_49', 'Fungus3_50', 'Room_Queen'],
    city: ['Crossroads_49b', 'Room_nailsmith', 'Ruins1_01', 'Ruins1_02', 'Ruins1_03', 'Ruins1_04', 'Ruins1_05', 'Ruins1_05b', 'Ruins1_05c', 'Ruins1_06', 'Ruins1_09', 'Ruins1_17', 'Ruins1_18', 'Ruins1_23', 'Ruins1_24', 'Ruins1_25', 'Ruins1_27', 'Ruins1_28', 'Ruins1_29', 'Ruins1_30', 'Ruins1_31', 'Ruins1_31b', 'Ruins1_32', 'Ruins2_01', 'Ruins2_01_b', 'Ruins2_03', 'Ruins2_03b', 'Ruins2_04', 'Ruins2_05', 'Ruins2_06', 'Ruins2_07', 'Ruins2_08', 'Ruins2_09', 'Ruins2_10b', 'Ruins2_11', 'Ruins2_11_b', 'Ruins2_Watcher_Room', 'Ruins_Bathhouse', 'Ruins_Elevator', 'Ruins_House_01', 'Ruins_House_02', 'Ruins_House_03'],
    waterways: ['Abyss_01', 'Abyss_02', 'GG_Pipeway', 'GG_Waterways', 'Room_GG_Shortcut', 'Waterways_01', 'Waterways_02', 'Waterways_03', 'Waterways_04', 'Waterways_04b', 'Waterways_05', 'Waterways_06', 'Waterways_07', 'Waterways_08', 'Waterways_09', 'Waterways_12', 'Waterways_13', 'Waterways_14', 'Waterways_15'],
    crystal: ['Mines_01', 'Mines_02', 'Mines_03', 'Mines_04', 'Mines_05', 'Mines_06', 'Mines_07', 'Mines_10', 'Mines_11', 'Mines_13', 'Mines_16', 'Mines_17', 'Mines_18', 'Mines_19', 'Mines_20', 'Mines_23', 'Mines_24', 'Mines_25', 'Mines_28', 'Mines_29', 'Mines_30', 'Mines_31', 'Mines_32', 'Mines_34', 'Mines_35', 'Mines_36', 'Mines_37'],
    resting: ['Crossroads_46b', 'Crossroads_50', 'RestingGrounds_02', 'RestingGrounds_04', 'RestingGrounds_05', 'RestingGrounds_06', 'RestingGrounds_07', 'RestingGrounds_08', 'RestingGrounds_09', 'RestingGrounds_10', 'RestingGrounds_12', 'RestingGrounds_17', 'Room_Mansion', 'Room_Tram_RG', 'Ruins2_10'],
    deepnest: ['Abyss_03_b', 'Deepnest_01b', 'Deepnest_02', 'Deepnest_03', 'Deepnest_09', 'Deepnest_10', 'Deepnest_14', 'Deepnest_16', 'Deepnest_17', 'Deepnest_26', 'Deepnest_26b', 'Deepnest_30', 'Deepnest_31', 'Deepnest_32', 'Deepnest_33', 'Deepnest_34', 'Deepnest_35', 'Deepnest_36', 'Deepnest_37', 'Deepnest_38', 'Deepnest_39', 'Deepnest_40', 'Deepnest_41', 'Deepnest_42', 'Deepnest_44', 'Deepnest_45_v02', 'Deepnest_Spider_Town', 'Fungus2_25', 'Room_Mask_Maker', 'Room_Tram', 'Room_spider_small'],
    basin: ['Abyss_03', 'Abyss_04', 'Abyss_05', 'Abyss_17', 'Abyss_18', 'Abyss_19', 'Abyss_20', 'Abyss_21', 'Abyss_22'],
    abyss: ['Abyss_06_Core', 'Abyss_08', 'Abyss_09', 'Abyss_10', 'Abyss_12', 'Abyss_15', 'Abyss_16', 'Abyss_Lighthouse_room'],
    edge: ['Abyss_03_c', 'Deepnest_East_01', 'Deepnest_East_02', 'Deepnest_East_03', 'Deepnest_East_04', 'Deepnest_East_06', 'Deepnest_East_07', 'Deepnest_East_08', 'Deepnest_East_09', 'Deepnest_East_10', 'Deepnest_East_11', 'Deepnest_East_12', 'Deepnest_East_13', 'Deepnest_East_14', 'Deepnest_East_14b', 'Deepnest_East_15', 'Deepnest_East_16', 'Deepnest_East_17', 'Deepnest_East_18', 'Deepnest_East_Hornet', 'GG_Lurker', 'Room_Wyrm', 'Room_nailmaster_03'],
    hive: ['Hive_01', 'Hive_02', 'Hive_03', 'Hive_03_c', 'Hive_04', 'Hive_05'],
    colosseum: ['Room_Colosseum_01', 'Room_Colosseum_02', 'Room_Colosseum_Bronze', 'Room_Colosseum_Gold', 'Room_Colosseum_Silver', 'Room_Colosseum_Spectate'],
    cliffs: ['Cliffs_01', 'Cliffs_02', 'Cliffs_03', 'Cliffs_04', 'Cliffs_05', 'Cliffs_06', 'Fungus1_28', 'Room_nailmaster'],
    palace: ['White_Palace_01', 'White_Palace_02', 'White_Palace_03_hub', 'White_Palace_04', 'White_Palace_05', 'White_Palace_06', 'White_Palace_07', 'White_Palace_08', 'White_Palace_09', 'White_Palace_11', 'White_Palace_12', 'White_Palace_13', 'White_Palace_14', 'White_Palace_15', 'White_Palace_16', 'White_Palace_17', 'White_Palace_18', 'White_Palace_19', 'White_Palace_20'],
  };
  /* The places inside an area, with the title the game shows on entering them, and their rooms. */
  const PLACES = {
    'kingspass': { es: 'Paso del Rey', en: 'King\'s Pass' },   // KINGSPASS_SUPER/_MAIN/_SUB
    'eggtemple': { es: 'Templo del Huevo Negro', en: 'Temple of the Black Egg' },   // EGGTEMPLE_SUPER/_MAIN/_SUB
    'shamantemple': { es: 'Montículo Ancestral', en: 'Ancestral Mound' },   // SHAMANTEMPLE_SUPER/_MAIN/_SUB
    'acid_lake': { es: 'Lago de Unn', en: 'Lake of Unn' },   // ACID_LAKE_SUPER/_MAIN/_SUB
    'noeyes_temple': { es: 'Santuario de Piedra', en: 'Stone Sanctuary' },   // NOEYES_TEMPLE_SUPER/_MAIN/_SUB
    'overgrown_mound': { es: 'Montículo Descuidado', en: 'Overgrown Mound' },   // OVERGROWN_MOUND_SUPER/_MAIN/_SUB
    'queens_station': { es: 'Estación de la Reina', en: 'Queen\'s Station' },   // QUEENS_STATION_SUPER/_MAIN/_SUB
    'mantis_village': { es: 'Poblado Mantis', en: 'Mantis Village' },   // MANTIS_VILLAGE_SUPER/_MAIN/_SUB
    'fungus_core': { es: 'Núcleo Fúngico', en: 'Fungal Core' },   // FUNGUS_CORE_SUPER/_MAIN/_SUB
    'monomon_archive': { es: 'Archivos de la Maestra', en: 'Teacher\'s Archives' },   // MONOMON_ARCHIVE_SUPER/_MAIN/_SUB
    'mage_tower': { es: 'Santuario de Almas', en: 'Soul Sanctum' },   // MAGE_TOWER_SUPER/_MAIN/_SUB
    'kings_station': { es: 'Estación del Rey', en: 'King\'s Station' },   // KINGS_STATION_SUPER/_MAIN/_SUB
    'love_tower': { es: 'Torre del Amor', en: 'Tower of Love' },   // LOVE_TOWER_SUPER/_MAIN/_SUB
    'bathhouse': { es: 'Casa de los Placeres', en: 'Pleasure House' },   // BATHHOUSE_SUPER/_MAIN/_SUB
    'peak': { es: 'Corona de Hallownest', en: 'Hallownest\'s Crown' },   // PEAK_SUPER/_MAIN/_SUB
    'crystal_mound': { es: 'Montículo Cristalizado', en: 'Crystalised Mound' },   // CRYSTAL_MOUND_SUPER/_MAIN/_SUB
    'spider_village': { es: 'Poblado Distante', en: 'Distant Village' },   // SPIDER_VILLAGE_SUPER/_MAIN/_SUB
    'ruined_tramway': { es: 'Tranvía Fallido', en: 'Failed Tramway' },   // RUINED_TRAMWAY_SUPER/_MAIN/_SUB
    'weavers_den': { es: 'Guarida de las Tejedoras', en: 'Weavers\' Den' },   // WEAVERS_DEN_SUPER/_MAIN/_SUB
    'hegemol_nest': { es: 'Guarida de las Bestias', en: 'Beast\'s Den' },   // HEGEMOL_NEST_SUPER/_MAIN/_SUB
    'stagnest': { es: 'Nido de ciervos', en: 'Stag Nest' },   // STAGNEST_SUPER/_MAIN/_SUB
    'wyrmskin': { es: 'Coraza desechada', en: 'Cast-Off Shell' },   // WYRMSKIN_SUPER/_MAIN/_SUB
    'blue_lake': { es: 'Lago Azul', en: 'Blue Lake' },   // BLUE_LAKE_SUPER/_MAIN/_SUB
    'glade': { es: 'Claro de la Esperanza', en: 'Spirits\' Glade' },   // GLADE_SUPER/_MAIN/_SUB
    'godseeker_waste': { es: 'Pila de Basura', en: 'Junk Pit' },   // GODSEEKER_WASTE_SUPER/_MAIN/_SUB
    'ismas_grove': { es: 'Arboleda de Isma', en: 'Isma\'s Grove' },   // ISMAS_GROVE_SUPER/_MAIN/_SUB
    'palace_grounds': { es: 'Tierras de Palacio', en: 'Palace Grounds' },   // PALACE_GROUNDS_SUPER/_MAIN/_SUB
    'path_of_sacrifice': { es: 'Sendero del Dolor', en: 'Path Of Pain' },   // PATH_OF_SACRIFICE_SUPER/_MAIN/_SUB
  };
  const BY_PLACE = {
    kingspass: ['Tutorial_01'],
    eggtemple: ['Room_temple'],
    shamantemple: ['Crossroads_ShamanTemple'],
    acid_lake: ['Fungus1_26', 'Fungus1_Slug', 'Room_Slug_Shrine'],
    noeyes_temple: ['Fungus1_35', 'Fungus1_36'],
    overgrown_mound: ['Room_Fungus_Shaman'],
    queens_station: ['Fungus2_01', 'Fungus2_02', 'Fungus2_34'],
    mantis_village: ['Fungus2_12', 'Fungus2_13', 'Fungus2_14', 'Fungus2_15', 'Fungus2_23', 'Fungus2_31'],
    fungus_core: ['Fungus2_29', 'Fungus2_30'],
    monomon_archive: ['Fungus3_archive', 'Fungus3_archive_02'],
    mage_tower: ['Ruins1_09', 'Ruins1_23', 'Ruins1_24', 'Ruins1_25', 'Ruins1_30', 'Ruins1_32'],
    kings_station: ['Ruins2_05', 'Ruins2_06', 'Ruins2_07', 'Ruins2_08', 'Ruins2_09', 'Ruins2_10b'],
    love_tower: ['Ruins2_11', 'Ruins2_11_b'],
    bathhouse: ['Ruins_Bathhouse', 'Ruins_Elevator'],
    peak: ['Mines_25', 'Mines_34'],
    crystal_mound: ['Mines_35'],
    spider_village: ['Deepnest_09', 'Deepnest_10', 'Room_spider_small'],
    ruined_tramway: ['Deepnest_14', 'Deepnest_26', 'Deepnest_26b'],
    weavers_den: ['Deepnest_45_v02'],
    hegemol_nest: ['Deepnest_Spider_Town'],
    stagnest: ['Cliffs_03'],
    wyrmskin: ['Deepnest_East_Hornet', 'Room_Wyrm'],
    blue_lake: ['Crossroads_50'],
    glade: ['RestingGrounds_08'],
    godseeker_waste: ['GG_Waterways', 'Room_GG_Shortcut'],
    ismas_grove: ['Waterways_13'],
    palace_grounds: ['Abyss_05', 'Abyss_22'],
    path_of_sacrifice: ['White_Palace_17', 'White_Palace_18', 'White_Palace_19', 'White_Palace_20'],
  };
  const SCENE = {}, SCENE_PLACE = {};
  for (const [id, list] of Object.entries(BY_AREA)) for (const s of list) SCENE[s] = id;
  for (const [id, list] of Object.entries(BY_PLACE)) for (const s of list) SCENE_PLACE[s] = id;
  const areaOf = (scene) => (typeof scene !== 'string' ? '' : SCENE[scene] || (scene.startsWith('GG_') ? 'godhome' : ''));
  const placeOf = (scene) => (typeof scene === 'string' && SCENE_PLACE[scene]) || '';
  HK.rooms = { AREAS, PLACES, SCENE, areaOf, placeOf };
  if (typeof module !== 'undefined' && module.exports) module.exports = HK.rooms;
})();
