#!/usr/bin/env node
/* tools/artpack.js — the copy of the site that's published as an Artifact.
   An Artifact allows at most 255 files per version and the site has over 480: 180 portraits
   (assets/enemies/) and 163 medallions (assets/journal/) are most of them. Those two folders
   are packed into js/artpack.js as data: URIs (HK.artpack['enemies/<id>']), which D.art()
   checks before the path; everything else is copied as is, and index.html loads that script
   just before js/app.js, the first of the page's own. No dependencies.
   Usage: node tools/artpack.js <folder>          (npm run artpack -- <folder>)
   Leaves the site ready to publish in <folder> and writes the file list to the output. */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PACKED = ['enemies', 'journal'];
const LIMIT = 255;

const out = process.argv[2];
if (!out) {
  console.error('Usage: node tools/artpack.js <folder>');
  process.exit(1);
}
const OUT = path.resolve(out);
if (OUT === ROOT || ROOT.startsWith(OUT + path.sep)) {
  console.error("The output folder can't be the project or contain it.");
  process.exit(1);
}
// Only a folder that's already a previous copy (the one with js/artpack.js) is emptied.
if (fs.existsSync(OUT) && fs.readdirSync(OUT).length) {
  if (!fs.existsSync(path.join(OUT, 'js', 'artpack.js'))) {
    console.error(`${OUT} isn't empty and isn't a previous copy: leaving it alone.`);
    process.exit(1);
  }
  fs.rmSync(OUT, { recursive: true });
}

const files = [];
const put = (rel, data) => {
  fs.mkdirSync(path.dirname(path.join(OUT, rel)), { recursive: true });
  fs.writeFileSync(path.join(OUT, rel), data);
  files.push(rel);
};
const walk = (rel) => fs.readdirSync(path.join(ROOT, rel), { withFileTypes: true })
  .sort((a, b) => a.name.localeCompare(b.name))
  .flatMap((d) => (d.isDirectory() ? walk(`${rel}/${d.name}`) : [`${rel}/${d.name}`]));

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const APP = '<script src="js/app.js"></script>';
if (!html.includes(APP)) {
  console.error(`index.html no longer loads ${APP}: check where js/artpack.js goes.`);
  process.exit(1);
}
put('index.html', html.replace(APP, `<script src="js/artpack.js"></script>\n${APP}`));

for (const rel of [...walk('css'), ...walk('js')]) put(rel, fs.readFileSync(path.join(ROOT, rel)));

const pack = {};
let bytes = 0;
for (const group of fs.readdirSync(path.join(ROOT, 'assets')).sort()) {
  for (const rel of walk(`assets/${group}`)) {
    const buf = fs.readFileSync(path.join(ROOT, rel));
    if (!PACKED.includes(group)) { put(rel, buf); continue; }
    if (!rel.endsWith('.png')) throw new Error(`${rel}: only PNGs are packed`);
    pack[`${group}/${path.basename(rel, '.png')}`] = `data:image/png;base64,${buf.toString('base64')}`;
    bytes += buf.length;
  }
}
put('js/artpack.js', `/* js/artpack.js — generated by tools/artpack.js; not edited by hand.
   Portraits and medallions (${PACKED.map((g) => `assets/${g}/`).join(', ')}) as data: URIs, for the copy
   published as an Artifact, which allows no more than ${LIMIT} files. D.art() checks them before
   the path. */
(() => {
  'use strict';
  const HK = globalThis.HK || (globalThis.HK = {});
  HK.artpack = ${JSON.stringify(pack, null, 1)};
})();
`);

const kb = (n) => `${Math.round(n / 1024)} KB`;
console.error(`${Object.keys(pack).length} images packed (${kb(bytes)} → ${kb(fs.statSync(path.join(OUT, 'js/artpack.js')).size)} in js/artpack.js)`);
console.error(`${files.length} files in ${OUT} (limit: ${LIMIT})`);
if (files.length > LIMIT) {
  console.error("They don't fit: pack another assets/ folder (PACKED).");
  process.exit(1);
}
console.log(JSON.stringify(files));
