#!/usr/bin/env node
/* tools/fetch-rooms.js — generates js/rooms.js: which area each of the game's rooms (its scenes,
   "Crossroads_47", "GG_Atrium") belongs to, and each area's name as the game writes it.
   `npm run rooms`. No dependencies; needs Node 18 (fetch).

   Sources:
     · the room → area table: the community randomizer's rooms.json (homothetyhk/RandomizerMod,
       pinned to a commit), which gives each scene its map area and its titled area. Only that
       fact is taken, one area id per scene.
     · the names: the game's own text (kb/data/all_text.json, see tools/game-text.js), with the
       key next to each one: MAP_NAME_<X> for the map's areas, <X>_SUPER + <X>_MAIN for the rest.
   The rooms the randomizer leaves out and a save can name (Godhome's GG_*, the two trams) are
   added below by hand. */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOMS = 'https://raw.githubusercontent.com/homothetyhk/RandomizerMod/'
  + 'cad3d5a7b73ed3ddf4af43795b20c23ced14bb4c/RandomizerMod/Resources/Data/rooms.json';
const TEXT = path.join(__dirname, '..', 'kb', 'data', 'all_text.json');
const OUT = path.join(__dirname, '..', 'js', 'rooms.js');

/* The site's areas: its id, the text keys of its name (joined with a space) and the area light it
   takes (css/tokens.css, --area-*; '' for none: the Howling Cliffs have no measured palette).
   Two regions the game's map paints in one tint take the other's light, as in js/app-arena.js. */
const AREAS = [
  ['dirtmouth', ['MAP_NAME_DIRTMOUTH'], 'dirtmouth'],
  ['crossroads', ['MAP_NAME_CROSSROADS'], 'crossroads'],
  ['greenpath', ['MAP_NAME_GREENPATH'], 'greenpath'],
  ['fungal', ['MAP_NAME_FUNGAL_WASTES'], 'fungal'],
  ['fog', ['MAP_NAME_FOG_CANYON'], 'gardens'],
  ['gardens', ['MAP_NAME_ROYAL_GARDENS'], 'gardens'],
  ['city', ['MAP_NAME_CITY'], 'city'],
  ['waterways', ['MAP_NAME_WATERWAYS'], 'fungal'],
  ['crystal', ['MAP_NAME_MINES'], 'crystal'],
  ['resting', ['MAP_NAME_RESTING_GROUNDS'], 'resting'],
  ['deepnest', ['MAP_NAME_DEEPNEST'], 'deepnest'],
  ['basin', ['MAP_NAME_ABYSS'], 'basin'],
  ['abyss', ['ABYSS_DEEP_SUPER', 'ABYSS_DEEP_MAIN'], 'abyss'],
  ['edge', ['MAP_NAME_OUTSKIRTS'], 'edge'],
  ['hive', ['HIVE_MAIN'], 'hive'],
  ['colosseum', ['COLOSSEUM_MAIN', 'COLOSSEUM_SUB'], 'colosseum'],
  ['cliffs', ['MAP_NAME_CLIFFS'], ''],
  ['palace', ['WHITE_PALACE_SUPER', 'WHITE_PALACE_MAIN'], 'palace'],
  ['godhome', ['GODHOME_MAIN'], 'godhome'],
];
// The randomizer's map area → the site's area; a titled area that has its own wins.
const MAP_AREA = {
  'Dirtmouth': 'dirtmouth', 'Forgotten Crossroads': 'crossroads', 'Greenpath': 'greenpath',
  'Fungal Wastes': 'fungal', 'Fog Canyon': 'fog', "Queen's Gardens": 'gardens', 'City of Tears': 'city',
  'Royal Waterways': 'waterways', 'Crystal Peak': 'crystal', 'Resting Grounds': 'resting', 'Deepnest': 'deepnest',
  'Ancient Basin': 'basin', "Kingdom's Edge": 'edge', 'Howling Cliffs': 'cliffs', 'White Palace': 'palace',
};
const TITLED = { 'Hive': 'hive', 'Colosseum': 'colosseum', 'Abyss': 'abyss' };
// Rooms the randomizer doesn't list. The trams' cars are counted where their line runs.
const EXTRA = { 'Room_Tram': 'deepnest', 'Room_Tram_RG': 'resting' };

const norm = (s) => String(s).replace(/[’‘]/g, "'").replace(/[“”]/g, '"').replace(/\s+/g, ' ').trim();
const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

(async () => {
  if (!fs.existsSync(TEXT)) throw new Error('kb/data/all_text.json is missing: run `npm run text -- --key MAP_NAME_` once');
  const text = JSON.parse(fs.readFileSync(TEXT, 'utf8'));
  const res = await fetch(ROOMS, { headers: { 'User-Agent': 'hallownest-calculator (fetch-rooms.js)' } });
  if (!res.ok) throw new Error('HTTP ' + res.status);
  const rooms = await res.json();

  const scenes = {};
  for (const r of Object.values(rooms)) {
    const id = TITLED[r.TitledArea] || MAP_AREA[r.MapArea];
    if (id) scenes[r.SceneName] = id;
  }
  Object.assign(scenes, EXTRA);

  const lines = AREAS.map(([id, keys, light]) => {
    const name = (lang) => norm(keys.map((k) => {
      if (text[lang][k] === undefined) throw new Error('no text ' + k);
      return text[lang][k];
    }).join(' '));
    return `    ${q(id)}: { es: ${q(name('ES'))}, en: ${q(name('EN'))}, light: ${q(light)} },   // ${keys.join(' + ')}`;
  });
  const byArea = {};
  for (const [scene, id] of Object.entries(scenes).sort()) (byArea[id] = byArea[id] || []).push(scene);
  const sceneLines = AREAS.filter(([id]) => byArea[id]).map(([id]) => `    ${id}: [${byArea[id].map(q).join(', ')}],`);

  fs.writeFileSync(OUT, [
    '/* js/rooms.js — GENERATED by tools/fetch-rooms.js (`npm run rooms`): don\'t edit by hand.',
    '   The game\'s areas, each with its name as the game writes it (the text key alongside) and the',
    '   area light it takes (css/tokens.css, --area-*); and which area each room (scene) is in, from',
    '   the community randomizer\'s rooms.json. areaOf(scene) → the area id, or \'\'. Godhome\'s rooms',
    '   (GG_*) are all Godhome. */',
    '(() => {',
    "  'use strict';",
    '  const HK = globalThis.HK || (globalThis.HK = {});',
    '  const AREAS = {',
    ...lines,
    '  };',
    '  const BY_AREA = {',
    ...sceneLines,
    '  };',
    '  const SCENE = {};',
    '  for (const [id, list] of Object.entries(BY_AREA)) for (const s of list) SCENE[s] = id;',
    "  const areaOf = (scene) => (typeof scene !== 'string' ? '' : SCENE[scene] || (scene.startsWith('GG_') ? 'godhome' : ''));",
    '  HK.rooms = { AREAS, SCENE, areaOf };',
    "  if (typeof module !== 'undefined' && module.exports) module.exports = HK.rooms;",
    '})();',
    '',
  ].join('\n'));
  console.log(`js/rooms.js: ${AREAS.length} areas, ${Object.keys(scenes).length} rooms`);
})().catch((e) => { console.error(e.message); process.exitCode = 1; });
